-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MediaWikiMessenger/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE mw_messenger_channel (
  mw_messenger_channel_id SERIAL NOT NULL,
  name TEXT NOT NULL,
  is_deleted BOOLEAN DEFAULT true NOT NULL,
  is_chatmods_private BOOLEAN DEFAULT false NOT NULL,
  is_chatadmins_private BOOLEAN DEFAULT false NOT NULL,
  is_writing_restricted_to_chatmods BOOLEAN DEFAULT false NOT NULL,
  is_writing_restricted_to_chatadmins BOOLEAN DEFAULT false NOT NULL,
  PRIMARY KEY(mw_messenger_channel_id)
);


CREATE TABLE mw_messenger_message (
  mw - messenger_message_id SERIAL NOT NULL,
  mw - messenger_message_user_id INT NOT NULL,
  mw - messenger_message_channel_id INT NOT NULL,
  is_editing_restricted_to_chatmods BOOLEAN DEFAULT false NOT NULL,
  is_editing_restricted_to_chatadmins BOOLEAN DEFAULT false NOT NULL,
  is_deleted BOOLEAN DEFAULT true NOT NULL,
  PRIMARY KEY(mw - messenger_message_id)
);


CREATE TABLE mw_messenger_message_revision (
  mw_messenger_message_revision_id SERIAL NOT NULL,
  mw_messenger_message_revision_user_id INT NOT NULL,
  mw - messenger_message_channel_id INT NOT NULL,
  is_deleted BOOLEAN DEFAULT true NOT NULL,
  PRIMARY KEY(
    mw_messenger_message_revision_id
  )
);
