-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MediaWikiMessenger/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mw_messenger_channel (
  mw_messenger_channel_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  name LONGTEXT NOT NULL,
  is_deleted TINYINT(1) DEFAULT 1 NOT NULL,
  is_chatmods_private TINYINT(1) DEFAULT 0 NOT NULL,
  is_chatadmins_private TINYINT(1) DEFAULT 0 NOT NULL,
  is_writing_restricted_to_chatmods TINYINT(1) DEFAULT 0 NOT NULL,
  is_writing_restricted_to_chatadmins TINYINT(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY(mw_messenger_channel_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/mw_messenger_message (
  mw - messenger_message_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mw - messenger_message_user_id INT NOT NULL,
  mw - messenger_message_channel_id INT NOT NULL,
  is_editing_restricted_to_chatmods TINYINT(1) DEFAULT 0 NOT NULL,
  is_editing_restricted_to_chatadmins TINYINT(1) DEFAULT 0 NOT NULL,
  is_deleted TINYINT(1) DEFAULT 1 NOT NULL,
  PRIMARY KEY(mw - messenger_message_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/mw_messenger_message_revision (
  mw_messenger_message_revision_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  mw_messenger_message_revision_user_id INT NOT NULL,
  mw - messenger_message_channel_id INT NOT NULL,
  is_deleted TINYINT(1) DEFAULT 1 NOT NULL,
  PRIMARY KEY(
    mw_messenger_message_revision_id
  )
) /*$wgDBTableOptions*/;
