-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/MediaWikiMessenger/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mw_messenger_channel (
  mw_messenger_channel_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name CLOB NOT NULL, is_deleted BOOLEAN DEFAULT 1 NOT NULL,
  is_chatmods_private BOOLEAN DEFAULT 0 NOT NULL,
  is_chatadmins_private BOOLEAN DEFAULT 0 NOT NULL,
  is_writing_restricted_to_chatmods BOOLEAN DEFAULT 0 NOT NULL,
  is_writing_restricted_to_chatadmins BOOLEAN DEFAULT 0 NOT NULL
);


CREATE TABLE /*_*/mw_messenger_message (
  mw - messenger_message_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mw - messenger_message_user_id INTEGER NOT NULL,
  mw - messenger_message_channel_id INTEGER NOT NULL,
  is_editing_restricted_to_chatmods BOOLEAN DEFAULT 0 NOT NULL,
  is_editing_restricted_to_chatadmins BOOLEAN DEFAULT 0 NOT NULL,
  is_deleted BOOLEAN DEFAULT 1 NOT NULL
);


CREATE TABLE /*_*/mw_messenger_message_revision (
  mw_messenger_message_revision_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  mw_messenger_message_revision_user_id INTEGER NOT NULL,
  mw - messenger_message_channel_id INTEGER NOT NULL,
  is_deleted BOOLEAN DEFAULT 1 NOT NULL
);
